### ISSUE TITLE
Swift Compilation Errors

### ISSUE THREAD

**Issue by gowthamravichandran** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#10]
Hi,

When I try do cordova build ios or ionic build ios, I get the following error

`let pluginResult = CDVPluginResult(status: CDVCommandStatus_OK, messageAsDictionary: message as! [String : AnyObject])
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~

*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal i386 /Users/.../myPushApp/platforms/ios/HelloCordova/Plugins/ibm-mfp-core/CDVBMSClient.swift
    CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(2 failures)
`

Things work smoothly for android

can someone help to work around this ?

**Comment by mjparangot** [comment]
I'm am working on resolving this issue right now

**Comment by mjparangot** [comment]
Hi @gowthamravichandran 

This appears to be an issue with Cordova and certain plugins:

https://cordova.apache.org/announcements/2015/12/18/cordova-ios-4.0.1.html (See the comments)

https://forum.ionicframework.com/t/ios-build-fails-error-code-65/43835/6

I was able to run `cordova build ios` after doing the following:

`cordova platform remove ios`
`cordova platform add ios@3.9.0`

**Comment by gowthamravichandran** [comment]
Thanks.. that worked

Also Please update your docs to mention that the below line should be added to existing `didFinishLaunchingWithOptions` method. 

`[[CDVMFPPush sharedInstance] didReceiveRemoteNotificationOnLaunch:launchOptions];`

this would help others.
