### ISSUE TITLE
Module 'com.ibm.mobilefirstplatform.clientsdk.android:analytics:1.2.6' depends o n one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by gopi014** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#100]
Hi,
I am trying to integrate the BMS push to my ionic app and I am getting following error when I do 
ionic build android

:prepareDebugDependenciesModule 'com.ibm.mobilefirstplatform.clientsdk.android:a
nalytics:1.2.6' depends on one or more Android Libraries but is a jar
Module 'com.ibm.mobilefirstplatform.clientsdk.android:analytics:1.2.6' depends o
n one or more Android Libraries but is a jar

**Comment by AnanthaKrish** [comment]
@gopi014 Please try a `cordova plugin update `. this will fix the issue

**Comment by gopi014** [comment]
it is working fine now. thanks
