### ISSUE TITLE
Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?

### ISSUE THREAD

**Issue by andaqui** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#102]
With the latest update of xcode we get a new issue when trying to build.

```
Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
```
in BMSPushUtils.swift file, line 117, 118, 119 and 121. See printscreen.

![error](https://user-images.githubusercontent.com/988605/38249259-5976b220-374b-11e8-80ec-3419c871f808.png)

**Comment by AnanthaKrish** [comment]
@kumpanen Please use XCode 9.2 and try

**Comment by andaqui** [comment]
@AnanthaKrish Well yea, it worked last week with 9.2, but thats not a good solution in the long term imho. :)

**Comment by AnanthaKrish** [comment]
@kumpanen Yeah , I agree..  With latest Xcode we have to start testing, that will take couple of days. As a solution for now , please use Xcode 9.2 ...

**Comment by andaqui** [comment]
okay, thanks for the feedback.

**Comment by AnanthaKrish** [comment]
@kumpanen change the swift version to 4.1. In pods (All frameworks) and your project

**Comment by andaqui** [comment]
Swift version to 4.1 solves the issue. Thanks.
