### ISSUE TITLE
error building ios: Type 'BMSAnalytics' has no member 'callersUIViewController'

### ISSUE THREAD

**Issue by andaqui** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#104]
Hi.
Now we are getting error building ios again. The error is in bms-core/CDVBMSAnalytics.swift file.
```
Type 'BMSAnalytics' has no member 'callersUIViewController'
Type 'Analytics' has no member 'triggerFeedbackMode'
```
![screen shot 2018-04-27 at 14 37 10](https://user-images.githubusercontent.com/988605/39363471-b91c37a8-4a2a-11e8-9e13-fa0461486b7b.png)

I tested with an older version of the plugin and it worked to build without this error. 
Please advice.

**Comment by AnanthaKrish** [comment]
@kumpanen This is not a push plugin issue . Please raise this issue in https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core/issues .
