### ISSUE TITLE
Working with Xcode 9? [Error: “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift]

### ISSUE THREAD

**Issue by torsorensen** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#110]
Hi,
I'm on Xcode 9.4.1 and I'm sort of stuck at this error that comes from all the BMS pods listed in my Podfile (see below).

_The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor._

I've not let Xcode convert my code, but I've seen this description on the bms-core:

_Go to Build Settings > Use Legacy Swift Language.
You may need to do this with other Pod dependencies such as BMSAnalytics and BMSAnalyticsAPI._

This "Use Legacy Swift Language" does not seem to be an option. 

How do I proceed?

platform :ios, '8.0'
use_frameworks!
target 'ionicpushios' do
	pod 'BMSAnalytics', '~>2.0'
	pod 'BMSSecurity', '~>2.0'
	pod 'BMSCore', '~>2.3'
	pod 'BMSPush', '~>3.3'
end

**Comment by AnanthaKrish** [comment]
@torsorensen make the project and pods `Swift Language Version`  to the same version of swift. You will be able to find the option in `Build Settings`.
