### ISSUE TITLE
Error Building on iOS

### ISSUE THREAD

**Issue by belamrani** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#16]
Hello I'm not able to build the app on ios : 

i have the following error when i build the error : 

ld: warning: ignoring file Digital Transformation/Plugins/ibm-mfp-push/IMFPush.framework/IMFPush, missing required architecture x86_64 in file Digital Transformation/Plugins/ibm-mfp-push/IMFPush.framework/IMFPush (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IMFPushClient", referenced from:
      _globalinit_33_8AE6FF0ABDF9DB1E9C1A17B1E6D5E38E_func0 in CDVMFPPush.o
      Digital_Transformation.CDVMFPPush.__allocating_init () -> Digital_Transformation.CDVMFPPush in CDVMFPPush.o
      Digital_Transformation.CDVMFPPush.__allocating_init (webView : __ObjC.UIWebView!) -> Digital_Transformation.CDVMFPPush! in CDVMFPPush.o
      Digital_Transformation.CDVMFPPush.init () -> Digital_Transformation.CDVMFPPush in CDVMFPPush.o
      @objc Digital_Transformation.CDVMFPPush.init () -> Digital_Transformation.CDVMFPPush in CDVMFPPush.o
      function signature specialization <Arg[0] = Owned To Guaranteed> of Digital_Transformation.CDVMFPPush.init (webView : __ObjC.UIWebView!) -> Digital_Transformation.CDVMFPPush! in CDVMFPPush.o
      l_get_field_types_CDVMFPPush in CDVMFPPush.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I tried many times and i'm pretty sure i followed all the step. Any idea ?

**Comment by AnanthaKrish** [comment]
Fixed. There is no MFPPush now...
