### ISSUE TITLE
unregisterDevice function not working with iOS 10 / XCode 8

### ISSUE THREAD

**Issue by jmereaux** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#26]
Hi,

When trying to use the unregisterDevice function of the CDVMFPPush swift class, I get the following error:
`fatal error: unexpectedly found nil while unwrapping an Optional value`

The app crashes at the following line:
`self.push.unregisterDevice({ (response:IMFResponse!, error:NSError!) -> Void in`

Seems like self.push is nil.

Could it be a side effect due to the migration to iOS 10 / XCode 8?
Could you please help me to sort this out.

Thanks!

**Comment by AnanthaKrish** [comment]
Fixed
