### ISSUE TITLE
Unable to build ionic app using the ibm-mfp-push cordova plugin on Android (conflict with google-analytics cordova plugin)

### ISSUE THREAD

**Issue by jmereaux** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#27]
Hi,

I've been developing an Ionic app for several months, successfully using the [ibm-mfp-push](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push) plugin for Push Notifications.

I would now need to use the [cordova-plugin-google-analytics](https://github.com/danwilson/google-analytics-plugin) plugin.
I've added the plugin to my project and was able to make it work properly on iOS.

But when trying to build the project for android, I get the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzpz;
```

Seems like there is a conflict between ibm-mfp-push and cordova-google-analytics.

Could someone please provide some help?

Thanks

**Comment by AnanthaKrish** [comment]
works with new bms-push plugin .

**Comment by somnathbm** [comment]
@AnanthaKrish - Can you please help me in deciding how do I use bms-core plugin. I am on Ionic 2 project. 

I have tried to call BMSClient directly inside the platform ready in app.component.ts. But no success. The error throws "cannot find module BMSClient". If I try to import the bms-core plugins directory, it still says so.

Here is the snippet.

```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';

import { Dashboard } from '../pages/dashboard/dashboard';


@Component({
  templateUrl: 'app.html'
})
export class Fusion {
  rootPage = Dashboard;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();

      BMSClient.initialize(BMSClient.REGION_US_SOUTH);
    });
  }
}

```

**Comment by AnanthaKrish** [comment]
Try this way - https://github.com/ibm-bluemix-push-notifications/Ionic3_Hellopush/blob/8b50c4bcf96fea8a17b04e84b4398363130eb19b/hello_push/src/app/app.module.ts#L8
