### ISSUE TITLE
Can't register devices in production mode

### ISSUE THREAD

**Issue by errolNOTRS** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#3]
We are successfully registering devices in sandbox mode, but fail to register devices in production mode. Is there a config value to tell the plugin to use production mode?

**Comment by dgonz7** [comment]
By sandbox vs production, what do you mean exactly? Bluemix, GCM, APNS, or what? Also, what error(s) are you getting?

**Comment by errolNOTRS** [comment]
We are using the plugin in conjunction with the BlueMix IBM Push Notification Service.

We don’t get an error. We get a success, but see no devices registered. I do see a device is already registered message in the xCode device console which makes me think the plugin in always registering devices to the Sandbox environment in BlueMix.

How does the plugin know to register against the Sandbox vs Production devices in BlueMix?

Thanks,
Errol

**Comment by dgonz7** [comment]
Sandbox vs Production is something that is relevant on the Bluemix service, not on the client side. Once you switch to Production mode, you should just be able to register again and it should show up. More details here: https://www.ng.bluemix.net/docs/services/mobilepush/c_sandbox.html

Are those instructions the ones that you followed to switch over, and then it wouldn't register again?

**Comment by errolNOTRS** [comment]
This solved our problem. I was not aware that we had to flip the mode on the BlueMix side. Thanks for the quick replies. I tested and we’re good.
