### ISSUE TITLE
Ionic2 sample app available?

### ISSUE THREAD

**Issue by BerndGewehr** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#56]
Hi!

We want to start using bluemix push notifications in our all new ionic hybrid app.

Is there any demo git project to have a convenient start?

Thx!
Bernd

**Comment by AnanthaKrish** [comment]
@BerndGewehr Hi, you can see the sample here https://github.com/ibm-bluemix-push-notifications/Cordova_Ionic_HelloPush
