### ISSUE TITLE
with the updated cordova plugins w.r.t. push notifications not identified few of the libraries in xcode

### ISSUE THREAD

**Issue by vasuvuggu** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#69]
Hi All,
I have followed the following references for notifications w.r.t. ios,
https://github.com/ibm-bluemix-mobile-services/bms-samples-cordova-hellopush
& 
https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push

during building that project in xcode i am facing few of the issues as follows,
1)line   #import "XXXX-Swift.h"** in appdelete.m, - XXX-Swift.hfile not found
2)line import BMSCore,in  CDVBMSClient.Swift - no such module 'BMSCore', 
3)From xcode, Pods_XXX,Framework , in frameworks folder points to red in colour as well.
4)CDVBMSPush instance also unidentified -after clean & build it shows CDVBMSPush not defiend
5)& in the xcode/plugins folder some of the files have ended with .m,,.h & few with .swift extensions,

NOTE:
during xcode opens it asks for convert to swift version, but still i have discarded those changes & using 
obejctive c only.
these issues i am facing, after plugins updates, which is used to work previously.

thanks
srinivas.

**Comment by AnanthaKrish** [comment]
@vasuvuggu I think you are opening `.xcodeproj`  after doing `cordova prepare`, please open the `.xcworkspace` of your project.. 
<img width="350" alt="screen shot 2017-02-08 at 3 03 09 pm" src="https://cloud.githubusercontent.com/assets/16939018/22731173/c1d71138-ee0f-11e6-8d8b-3b371c8e8fb7.png">

**Comment by vasuvuggu** [comment]
thanks a lot for reply,
it resolves my issue.
