### ISSUE TITLE
unable to change android icon

### ISSUE THREAD

**Issue by belamrani** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#71]
Hello,

I would like to change the default android icon that appears when a notification is received. (it's a star by default).
Is it possible to define it in the options parameters used when we use registerDevice function ? Or is there an other way to do it ?

Thanks.

**Comment by AnanthaKrish** [comment]
You can add icon under res/drawable folder, with the client application. Then specify the name of the in android payload field in push dashboard .

Follow this - https://console.ng.bluemix.net/docs/services/mobilepush/c_android_enable.html#send_otpional_setting

**Comment by belamrani** [comment]
Thank you AnanthaKrish. It works perfectly 👍
