### ISSUE TITLE
iOS build fails when following documentation

### ISSUE THREAD

**Issue by gregackerman** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#76]
Under the section "updating your client application to use the Push SDK", there is an instruction to add this line at the top of AppDelegate.m:

#import "[your-project-name]-Swift.h"

After substituting my project name with underscores for dashes, it never finds this header file.  I have found that the following file seems to do the trick as the pch file actually exists and seems to satisfy the requirement to build the sample.
#import "bms-samples-cordova-push-Prefix.pch"

Could you check the doc steps on this?  Thanks.

**Comment by AnanthaKrish** [comment]
@gregackerman Usually it should work with the **#import "your_project_name-Swift.h"** .  Am not sure what causing problem for you. 

In the **AppDelegate.m** file , you will be able to see your project name in commented state somewhere between **line-19** and **Line-27**.
