### ISSUE TITLE
not working on ios

### ISSUE THREAD

**Issue by gabrielmancini** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#8]
pls some one can review the plugin?

**Comment by gabrielmancini** [comment]
solved.... u need bump version on npm

and on appdelegate i need to find the didFinishLaunchingWithOptions

and add this inside
[[CDVMFPPush sharedInstance] didReceiveRemoteNotificationOnLaunch:launchOptions];

**Comment by gabrielmancini** [comment]
<img width="872" alt="captura de tela 2016-02-24 as 3 39 58 pm" src="https://cloud.githubusercontent.com/assets/144915/13296569/f33a3834-db0c-11e5-8751-b059c3b310b7.png">

**Comment by gabrielmancini** [comment]
but still with error

**Comment by adrianopaladini** [comment]
Hi @gabrielmancini try to use the last version with my Pull: https://github.com/adrianopaladini/bms-clientsdk-cordova-plugin-push/commit/6d26bb6ab40b14ce00eaa257333c244f974213b6

**Comment by gabrielmancini** [comment]
other error
log:

```
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
Apache Cordova native platform version 3.8.0 is starting.
Multi-tasking -> Device: YES, App: YES
Unlimited access to network resources
[CDVTimer][splashscreen] 682.094991ms
[CDVTimer][statusbar] 27.978003ms
[CDVTimer][socialsharing] 38.814008ms
[CDVTimer][keyboard] 0.693977ms
[CDVTimer][TotalPluginStartup] 751.163006ms
Resetting plugins due to page load.
Finished load of: file:///var/mobile/Containers/Bundle/Application/4F7E7D4A-6C07-4423-B1BC-E7A5D935FFCC/XXX.app/www/index.html
Q4M started with settings: xxxxx
BMSClient: Success: 
registerDevice err:  The notification was blocked by user
Session Started successfully
```

**Comment by mjparangot** [comment]
I've updated npm

**Comment by gabrielmancini** [comment]
same error

**Comment by gabrielmancini** [comment]
there is some resolution to close this?

**Comment by mjparangot** [comment]
I tested the latest plugin from npm and I did not get any errors. Using v1.0.13

**Comment by gabrielmancini** [comment]
but not working too

**Comment by mjparangot** [comment]
the log error?

**Comment by gabrielmancini** [comment]
the certification push was invalid on customer account on apple :-( 

anyway solved now... thanks everyone!
