### ISSUE TITLE
Ionic 2 sample application

### ISSUE THREAD

**Issue by jmereaux** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#80]
Hi,

Is it possible to use the bms-push plugin with TypeScript and Ionic 2?
Is there any sample application available somewhere?

Thanks

**Comment by AnanthaKrish** [comment]
@jmereaux Hi, we have an ionic2 sample here - https://github.com/ibm-bluemix-push-notifications/Cordova_Ionic_HelloPush

**Comment by jmereaux** [comment]
@AnanthaKrish Thanks for your answer, but to me, your sample is for Ionic 1
