### ISSUE TITLE
Android app crashed when starting as result of receiving notification

### ISSUE THREAD

**Issue by tverilytt** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#91]
Hi!
My Android version of an app crashes when it receives a new notification. This happens when the app is not running (EDIT: or running in the background). If the app is running in foreground, all looks good.

I am on BMSPush 3.2.0.

Would really appreciate help and comments :-)

Cheers
-jo

----------

01-15 21:57:09.174  6475  6492 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
01-15 21:57:09.174  6475  6492 E AndroidRuntime: Process: com.torsmyr.myapp, PID: 6475
01-15 21:57:09.174  6475  6492 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPushIntentService.onUnhandled(MFPPushIntentService.java:183)
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPushIntentService.onMessageReceived(MFPPushIntentService.java:156)
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.zzl(Unknown Source)
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.zzJ(Unknown Source)
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at com.google.firebase.iid.zzb$1.run(Unknown Source)
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-15 21:57:09.174  6475  6492 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
A

**Comment by AnanthaKrish** [comment]
@tverilytt I found out the issue. Its in Android SDK. Will release a new version.

**Comment by tverilytt** [comment]
@AnanthaKrish Cool, thanks a lot :-)

**Comment by tverilytt** [comment]
@AnanthaKrish Things seem to be working again now, have you done any backend updates?!

**Comment by AnanthaKrish** [comment]
@tverilytt  Yeah I have updated the Android SDK..

**Comment by tverilytt** [comment]
@AnanthaKrish ok...does that mean I do not need to do any modifications? Can you elaborate on what the issue was, or should it not matter?!

**Comment by AnanthaKrish** [comment]
@tverilytt You don't have to update anything. Just rebuild the app , it will pull the latest dependencies. There was a String null pointer error in the Android SDK. That I have fixed.

**Comment by tverilytt** [comment]
Cool, thanks a lot!
