### ISSUE TITLE
ARC Semantic issue xcode 9

### ISSUE THREAD

**Issue by andaqui** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#93]
Hi.

Im having very irregular issues when building with xcode, it got it working once. After some days i retry to build the cordova project and to build through xcode but i always get "ARC Semantic issue" error in xcode so build fails.
I cant find any way to get through this now and i cannot find a solution. See printscreen. Any help would be appreciated.
![screen shot 2018-02-20 at 12 50 50](https://user-images.githubusercontent.com/988605/36422590-f7160bc8-163c-11e8-89d6-9bb16bdae20e.png)

**Comment by andaqui** [comment]
I noticed that if i run cordova plugin add bms-push as the last plugin install, it works to build through xcode again. Not sure why.

**Comment by AnanthaKrish** [comment]
@kumpanen Looks like iOS app is not able to link to CDVBMSPush . Add the push plugin after adding platforms, it should work fine then..

**Comment by andaqui** [comment]
I add the push plugin after adding cordova platform, but i have to install bms-push plugin last (after other cordova plugins installs), otherwise this error happens. Im not sure if its another cordova plugin conflicting or not.

**Comment by AnanthaKrish** [comment]
@kumpanen possibly yeah ... it’s conflict between plugin ..
